### PR TITLE
Shorten UniProt headers in run_plexedpiper output

### PR DESCRIPTION
**Pull request by TylerSagendorf**
Extract UniProt accession from full IDs. Also fixed the case where the dash between accessions and isoform numbers was incorrectly being replaced by an underscore.

### CODE REVIEW

**Comment by TylerSagendorf** [comment]
R-CMD-check failing on Windows due to an update to httput on 2023-01-12 (yesterday): https://github.com/rstudio/httpuv/issues/353

There is no issue with the actual code being checked. I verified this on my Windows machine using the latest version of R (4.2.2) and an older version of httput.

**Review by biodavidjm — COMMENTED** [review]
- I tested this PR on a human UniProt dataset and the outputs include all the improvements that we discussed. So that part is ready to go! Thanks!
- The test on rat RefSeq was also successful 
- However, the test on GENCODE using [this test dataset](https://drive.google.com/drive/folders/18jzWwpJKZC0lrtz1ResM498W3qZ3HMoe?usp=sharing) outputs the following warning:

```
Warning messages:
1: In eval(jsub, SDenv, parent.frame()) : NAs introduced by coercion
2: In eval(jsub, SDenv, parent.frame()) : NAs introduced by coercion
```

It would be great if you could take a look before merging, just in case is the tip of the iceberg.

**Comment by vladpetyuk** [comment]
What is the issue with the `ragg` package? The PlexedPiper doesn't pass the check.

**Comment by vladpetyuk** [comment]
Is the `ragg` package issue related to https://github.com/rstudio/httpuv/issues/353 ?

**Comment by TylerSagendorf** [comment]
> Is the `ragg` package issue related to [rstudio/httpuv#353](https://github.com/rstudio/httpuv/issues/353) ?

@vladpetyuk `ragg` was also updated on 1/12, so something might have broken. However, I was just able to install it on my Windows machine using the latest R version (4.2.2). I don't think it is related to any changes that I've made, since the checks pass on my machine, but I'm not sure why it is failing.

**Comment by TylerSagendorf** [comment]
> ```
> Warning messages:
> 1: In eval(jsub, SDenv, parent.frame()) : NAs introduced by coercion
> 2: In eval(jsub, SDenv, parent.frame()) : NAs introduced by coercion
> ```

@biodavidjm This is happening in `MSnID::parse_FASTA_names()`. The contaminant headers do not follow the format of the typical GENCODE entries, so they are not parsed correctly. Specifically, these warnings occur when converting the prot_length column from character to numeric. However, incorrect parsing of the contaminant headers does not matter, as they do not provide any useful information, they are removed when joining with the final results, and it does not affect the presence of contaminants in the final results.

**Results of parse_FASTA_names:**


**rii_peptide results table:**

**Comment by biodavidjm** [comment]
All right, so then it would be easy to get rid of the ugly warning. Why don't you first change to NA the "Contaminant" values and then convert them to numeric? Something like this...

```
df$prot_length[grepl("Contaminant", df$prot_length, ignore.case = TRUE)] <- NA
df$prot_length <- as.numeric(df$prot_length)
```
So if we get that warning again in the future, we will know that it is because of something else.

**Comment by TylerSagendorf** [comment]
> All right, so then it would be easy to get rid of the ugly warning. Why don't you first change to NA the "Contaminant" values and then convert them to numeric?

@biodavidjm Instead, I'll just remove contaminants before parsing, since `parse_FASTA_names` won't be able to extract any useful information from them.

**Comment by biodavidjm** [comment]
I really believe that we should keep contaminants. It can be a good QC to check if there are samples with more contaminants than others. This might be a QC test that we will include in the next round of QCs. It's been a very useful QC in many other projects (that even explained outlier samples). But even if we don't, the general public might want to do it. Please, do not remove them, use the 2 lines of code that I proposed. And contaminants should also be kept in the ratio files.

**Comment by TylerSagendorf** [comment]
> I really believe that we should keep contaminants. It can be a good QC to check if there are samples with more contaminants than others. This might be a QC test that we will include in the next round of QCs. It's been a very useful QC in many other projects (that even explained outlier samples). But even if we don't, the general public might want to do it. Please, do not remove them, use the 2 lines of code that I proposed. And contaminants should also be kept in the ratio files.

@biodavidjm As I said, removing the contaminants within `parse_FASTA_names` does not affect the final results… I’m only removing them from the function output because they do not parse, so all columns are just the contaminant headers.

**Comment by biodavidjm** [comment]
Sorry, I am not sure if I correctly understand. Are you saying that this is something that you propose to do? i.e., remove the contaminants before processing the data with `parse_FASTA_names` and then put the contaminants back?

If so, it works for me (as far as the contaminants are in the final outputs, we are happy)

**Comment by TylerSagendorf** [comment]
@biodavidjm The only purpose of `parse_FASTA_names` is to extract additional information from the FASTA headers. Since contaminant headers do not contain any useful information, removing them from the output of this function just means that the additional columns added to the `run_plexedpiper` output tables will be `NA` for contaminants. This is because we _left-join_ the `parse_FASTA_names` output to the tables created by the BIC helper functions that still include contaminants.

**Comment by biodavidjm** [comment]
If that fixes the warning, then, please go ahead! Let me know when the fix is done and I can do one final quick test before merging. Would that work?

**Review by vladpetyuk — APPROVED** [review]

**Pull request merged**
